### ISSUE TITLE
Feature Request - Env-wide Global Variables

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#13]
I've been having trouble trying to ensure some 'global' variables will always be available to templates.  When using partials and context / kwargs, they are lost.

The javascript version supports this through an implementation detail -- javascript just-so-happens to have global variables, and will look there.  The docs/wiki of the LinkedIn fork mentions this quite a bit.

It would be great if the AshesEnv class and/or render commands would support a globals dict.

**Comment by mahmoud** [comment]
So, a few years on, do we still feel we want these? I don't think I understood the feature at the time and was waiting for it to sink in or something. :P 

Seems like a useful feature potentially, and not impossible, I don't think.

**Comment by jvanasco** [comment]
My fault -- I didn't illustrate this with a test-case -- which I should have.

Just so others understand, I'll illustrate (from memory... I haven't touched the Javascript implementation for a while and don't want to)

In Python, Dust templates are rendered within the ashes rendering environment, `AshesEnv()`, which is somewhat sandboxed.  Unless something is defined via an extension or template model, it (mostly) doesn't exist.

In Javascript, Dust templates are rendered within a dust environment that can access global variables.  It's not sandboxed.  If something is undefined, dust can failover to globals -- because that's how javascript works.

So if we have a template like this:

    template_string = "{foo} {bar} {biz}"

In order to get this:

    1 2 3

Ashes requires a context that defines:

    {'foo': 1, 'bar': 2, 'biz':3 }

But javascript will accept this

    {'foo': 1, 'bar': 2}

And look into the globals for a definition of `biz`.

A way of potentially handling this in Ashes, would be to extend the `AshesEnv` instance with environment variables, and then extend the `Context` object's lookup to reference it.

I created a quick example in this commit (which may have broken other things, as I'm too lazy to run tests right now):

https://github.com/jvanasco/ashes/commit/34e951e6489dcedb2ba785e079b4ce3772fc1d1a


the usage would then be something like this:

    env_globals = {'biz': 3, }
    ashes_env = ashes.AshesEnv(['templates'], env_globals=env_globals)
    payload =  {'foo': 1, 'bar': 2}
    print ashes_env.render(Template(template_string), payload)
    >>> 1 2 3

**Comment by mahmoud** [comment]
Yeah! I like it, actually. As long as they're explicit, why not? And the implementation is nice and simple, too. I put some comments inline.

My only other thought: if they're the last place checked, how about calling them "defaults" or "default_values"? Is that too vague?

**Comment by jvanasco** [comment]
those are MUCH better names. i started with globals and globals_env, but had to rename to env_globals because of confusing namespace collisions with Ashes.

**Comment by mahmoud** [comment]
@jvanasco I committed your approach, and the changes I mentioned in the comments, plus a test case, seems to be working like a charm. Feel free to take it for a spin, I'll do a release shortly!
