### ISSUE TITLE
docs update or feature request - `load_all`

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#17]
`AshesEnv.load_all` only returns the templates; it does not register them into the environment.

`BaseAshesEnv.load_all` actually loads the templates.  it has a kwarg `do_register=True`, which then runs this bit:

    if do_register:
        for t in tmpls:
            self.register(t)

I'd suggest changing `AshesEnv.load_all` to have the same functionality  OR update the docstring to note that it doesn't actually load templates into the environment -- it just fetches them.

**Comment by jvanasco** [comment]
I just opened Ashes to do this myself, and noticed this commit:

    https://github.com/mahmoud/ashes/commit/548c6a12749858fe9b6bbdf7cf3114381c7d9241

It looks like i can close this?

**Comment by mahmoud** [comment]
Oh! Yes, as long as you find the behavior acceptable :)

**Comment by jvanasco** [comment]
I just did a test, and checked the source.   calling `load_all()` will get processed by the `AshesBaseEnv`, which loads via the template loaders' load_all, then the pipes those into register.  so everything registers now and it "works as expected" / much more efficiently.

**Comment by mahmoud** [comment]
Great! Thanks for running it through the paces.
