### ISSUE TITLE
possible feature idea - cacheable templates

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#18]
i have a novel idea for a feature, but it might not be possible.  i wanted to "ask first" before trying to build it.

we use the `dust` format for user customizable templates.  they're heavily sanitized and processed after submission, but are still User Generated Content.  dust.js handles client side, ashes handles server side rendering.

performance is a bit of a concern.  ashes is good enough for now, but we could do quite a bit better if we were able to cache the templates somehow.  A decent chunk of the time is spent compiling the templates.  

Since this is for user customization, we can't recycle the AshesEnv across requests.  Because of the way Ashes builds templates, neither the env not the templates can be serialized ( pickle doesn't like the render functions, probably doesn't like a lot more ).

In order to support cachable templates, I see a few opportunities:

• cache the _gen_python string.  This would save about 65% of building the template ( the 100% baseline is Template._get_render_func )
• cache the AST.  This would save about 45% of time loading the template, but might be easier.

My general concerns before moving forward, are that I'm not sure if this is 'legal' or not.    Could there be anything in the AST / python template that is specific to the current envelope or process ?  

i don't think so.  looking at the output of both, they seem doable -- but I don't have experience with the various filters and other advanced Dust techniques.  we just it with basic dict/string/list.

**Comment by jvanasco** [comment]
I finally had some time to get back to this (1 year and 1 day later!)

This branch is my first try - https://github.com/jvanasco/ashes/tree/feature-load_compiled

of note are the following files:

* tests_jv.py - shows normal, vs ast vs compiled loads
* ashes.py - i added in a timing section & decorated some functions for the tests.  i also made a public function `compile_python_string`

so far my learnings are this:

* processing a regular template is MUCH slower than loading compiled templates.
* there is little difference between loading an `ast` and a `python_string` , as they both need to be compiled.
* there is a noticeable difference between loading an `ast` and a `compiled(python_string)`.
amount to a difference of 1 second between the standard approach and a cached approach.  In a web server context, that is a pretty decent number.

I still need to play around with this to get the right functionality in there.  i think there is a use case for compiling everything within a template loader (if possible) or stashing a list of ast/compiled strings so they can be tracked by usage.  the use case I'm thinking of is that I may not want to compile 100 templates at once, but if I compiled 10 templates on a first usage... and another 10 on a second usage, I would want to be able to know that and cache the second 10 templates.  (that logic can be in developer-space.  i'm just concerned with making it accessible within ashes).

**Comment by jvanasco** [comment]
I closed the previous pull request (https://github.com/mahmoud/ashes/pull/26)

I've rebased against the current master and made the methods a bit leaner in this new branch:  

  https://github.com/jvanasco/ashes/tree/feature-compiled_support

Pros:
* Everything is largely documented inline
* the README is updated
* demos

Cons:
* Before issuing a PR, there is a bit of work (and I'm not sure how to proceed)...

# Tests

* I've created some tests but they exist as a standalone.  They're also a bit of a mix between benchmarks and demos.  
* I would like to expand the current test suite, but don't want to interrupt any of the reporting or other stuff you have in there.
* I would like to do a "benchmarks" section or tool, which can double as demos.  I'm also not sure the best way to split that out.  Maybe a "benchmarks" test file/folder?  I just think there should be something "official" to use for benchmarking template rendering, as that would make it better for people to hack on performance in the future.

# approach
* I implemented almost everything on the Template object itself; I used custom template loaders (examples in the tests_new directory) to illustrate pre-generation and lazy-generation of precompiled templates.  the older version had some convenience methods on the ashes Environment, but I think this is cleaner just on the Template object and using a custom loader (one can still manually call ".register" on the environment)

# test templates

Based on the suggestion from the old PR, I pulled out the templates from the `chert` project (and hacked the server to spit out json).  i've used that on the chert test file (which needs to be integrated into the test suites eventually).   this is a good start, but perhaps we should integrate other advanced templates and data models?  My use right now is rather limited, so maybe other users can propose some real-world dust templates from other open-source projects (or we agree on some?)

# breaking changes

This doesn't seem to break any standard/expected use.  Looking at the previous concerns:

* This leaves `Template.source` empty/as-none, but nothing should be accessing it.  
* I believe there was a concern over the auto-reload functionality in `BaseAshesEnv.load`.  That wouldn't raise an exception, because `source_file` would be `None` and bypass that block.  I think anyone using this functionality would probably be handling things via a custom loader -- as the point is to have an Env/Loader that does not have to persist, **however** it might probably make sense to put an int(epoch) on the Template object for the "last_generated" time (maybe even track first generation too?).

**Comment by mahmoud** [comment]
Wow, great work! Yes, this really has come a long way. I'm reviewing the code now, but I also wanted to point to [clastic's MetaApplication](https://github.com/mahmoud/clastic/tree/master/clastic) as another place I make medium usage of Ashes. Any devserver serves it right up, but data collection time probably outweighs rendering. 

Those performance gains are very impressive, but am I understanding correctly that the templates were being loaded once per render? I think the way I do it in Clastic wouldn't incur a lot of these costs to begin with. Still, excited for these results!

**Comment by mahmoud** [comment]
Looks pretty good! I definitely think the `last_generated = time.time()` is a good idea. Frankly kind of surprised I didn't already add that.

I think I'll do an editing pass of the docs after I merge the changes. The security concern mentioned is an interesting one, though it's easy to overstate. It may just be better to recommend that all cached files should be treated as code, i.e., stored securely, with attention paid to permissions.

**Comment by jvanasco** [comment]
Our use-case is basically a multi-tenant application, and the loader/env is short lived across an "internet scale" number of templating sets.  Imagine tumblr where every user/microsite is powered by a set of dust templates that are stashed in a database somewhere.  There is no guarantee that a given templating set will be used for more than one "page render" or that it would be rendered again by the same server on a subsequent request.  

Right now to handle the process growth, we just generate a new env/loader per request and use a cache of templates in redis.  Ideally I can eventually keep the env/ loader around and working like a LRU cache with some marshal/shelve magic and internal cleanup routines... But even then, we'll be recompiling templates often.

**Comment by mahmoud** [comment]
Right, right, I think you mentioned a bit about this before. Sounds great! Glad ashes is growing to better suit that use case. I'll keep an eye out for the PR and we'll get it handled real quick. :)

**Comment by mahmoud** [comment]
@jvanasco so now 17.0.0 is tested, packaged, and up on PyPI. Are we ok to close this issue, or is there more development and tracking you'd like to continue here?

**Comment by jvanasco** [comment]
I should have closed this on that merge!

**Comment by mahmoud** [comment]
No worries, I'm happy to close an issue, you did pretty much everything else! :)
