### ISSUE TITLE
support linkedin extensions: $idx, $len

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#23]
The linkedin fork introduced two extensions to the language:  https://github.com/linkedin/dustjs/wiki/Dust-Tutorial
- $idx - the index of the current iteration starting with zero (equivalent to `{@idx}{.}{/idx}`, however it's a primitive)
- $len - the number of elements in the data being iterated.

it would be great if ashes supported them.

**Comment by mahmoud** [comment]
:+1: I hope to get on that tonight.

**Comment by jvanasco** [comment]
oh wow!  thanks!  that saves me from trying to do this!

**Comment by mahmoud** [comment]
Closing this, as these two have been implemented for.. quite a while. :)
