### ISSUE TITLE
Nested lists broken

### ISSUE THREAD

**Issue by djrobstep** [mahmoud/ashes#28]
Trying to template a nested list as follows:

```
{#.}
row{~n}
{#.}
{.}{~n}
{/.}
{/.}
```

Given data of say: [[1,2], [3,4]]

You'd expect: 

```
row
1
2
row
3
4
```

as output, but instead, this happens:

```
Traceback (most recent call last):
  ...
  File ".../local/lib/python2.7/site-packages/ashes.py", line 1906, in render
    return tmpl.render(model, self)
  File ".../local/lib/python2.7/site-packages/ashes.py", line 1780, in render
    self.render_chunk(chunk, Context.wrap(env, model)).end()
  File ".../local/lib/python2.7/site-packages/ashes.py", line 1787, in render_chunk
    return self.render_func(chunk, context)
  File "<string>", line 11, in render
  File "<string>", line 4, in body_0
  File ".../local/lib/python2.7/site-packages/ashes.py", line 1572, in section
    head.pop('$len', None)
TypeError: pop() takes at most 1 argument (2 given)
```

**Comment by mahmoud** [comment]
Yeah, this is problematic, thank you for reporting it. I don't have a good design ready to support `$len` and other special variables in nested lists. I'm inclined to first fix the exception raising and then find a way to support it later.

**Comment by mahmoud** [comment]
Hm, not sure why GitHub isn't closing issues automatically, but as you can see in f241ea5, I've used @jvanasco's enhanced context to fix the issue while still supporting `$len` and `$idx` special variables. Expected output now generated:

```
row
1
2
row
3
4
``` 

([provided you set the whitespace flags correctly](https://github.com/mahmoud/ashes/blob/f241ea5c3ac2ff802ad6fe6a60582edf921c9b73/ashes.py#L2226))

**Comment by djrobstep** [comment]
Awesome :)

**Comment by mahmoud** [comment]
:) It's now in the PyPI version, as well (15.0.1)

**Comment by jvanasco** [comment]
I'm glad all that time I spent digging into the javascript dust behavior was useful for someone else too!
