### ISSUE TITLE
[feature request] split out/remove bottle code

### ISSUE THREAD

**Issue by jvanasco** [mahmoud/ashes#31]
It would be great if the `bottle` code were isolated away (or controlled by an environment variable)

These lines are what I'm referring to.

https://github.com/mahmoud/ashes/blob/master/ashes.py#L2129-L2176

It would be nice if the bottle import could be split out to another file, or at least suppressed with an environment variable.  We have `bottle` installed in our virtualenv for some specific services in a deployment (unrelated to an ashes process); having a dozen uswgi workers (re)start with an unnecessary 5.5MB load and memory hit is a bit annoying.

**Comment by mahmoud** [comment]
Wow, 5.5mb extra from that little bit? And yeah, I haven't used the bottle integration much beyond that initial point. Do you know of any templating libraries that split out their integration code like that. I'm looking for some conventions I could learn from. Alternatively, I can put it behind an env var that disables it, if that'd work for you.

**Comment by jvanasco** [comment]
Yeah. You can profile it with the `psutil` module 

    import os
    import psutil

    def get_mem():
        _process = psutil.Process(os.getpid())
        _mem = _process.get_memory_info()[0] / float(2 ** 20)
        return _mem
    
    print get_mem()
    import bottle
    print get_mem()
    del bottle
    print get_mem()

or just open 2 shell prompts -- one in Python and one straight unix/osx and check the memory as you add bottle.

most time's i've seen the integration handled from a framework or plugin - not the templating library.  

for example, `pyramid` ships a separate `pyramid_mako` and `pyramid_jinja2` library.  `flask` uses `jinja2` by importing it within flask.  (not the other way around).  

I think that anyone who cares about something like this would be fine with an ENV var, and migrating into a plugin or whatever would still necessitate something like a ENV flag during a deprecation period.

**Comment by jvanasco** [comment]
sidenote: I never realized just how good/optimized this code is.  i pored over it looking for any ways to speed things up... the generated templates are remarkably slim and the compiler itself is really lean.

**Comment by mahmoud** [comment]
Yeah fair enough on the first comment and thank you very much on the second! A lot of thanks is due to the original dustjs implementation, but a real big thank you to you for looking at it! I really hope to get back into giving ashes a full release very soon, so all help is greatly appreciated!

**Comment by jvanasco** [comment]
I've been hit with a bunch of bottlenecks around our Ashes implementation, so was looking for any ways to cheat how the CPython interpreter handles bytecode -- the little things like how loops and recursive code are implemented or how scope lookups are handled.  Everything is pretty tight in Ashes though.  I only saw one loop that looks like it could be rewritten in a way that performs better for larger templates (and would perform worse for smaller templates).

I'm re-writing my earlier PR to pre-compile templates and will hopefully have it done in a day or two.

The optimization that I'm eying right now is to enable the generation of a dict that represents the objects/attributes that are used/accessed on each template (including inheritance) or family of templates.  Maybe 20% of the data we pass into DustJS/Ashes is actually needed -- and that info could help on the data generation or what gets sent across processes/on the wire.
